# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from public.llmcloud.shimmanager.v1 import shim_service_pb2 as public_dot_llmcloud_dot_shimmanager_dot_v1_dot_shim__service__pb2


class ShimServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetQuery = channel.unary_unary(
                '/public.llmcloud.shimmanager.v1.ShimService/GetQuery',
                request_serializer=public_dot_llmcloud_dot_shimmanager_dot_v1_dot_shim__service__pb2.ShimServiceGetQueryRequest.SerializeToString,
                response_deserializer=public_dot_llmcloud_dot_shimmanager_dot_v1_dot_shim__service__pb2.ShimServiceGetQueryResponse.FromString,
                )


class ShimServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetQuery(self, request, context):
        """returns the query at the the top of the priority queue
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShimServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQuery,
                    request_deserializer=public_dot_llmcloud_dot_shimmanager_dot_v1_dot_shim__service__pb2.ShimServiceGetQueryRequest.FromString,
                    response_serializer=public_dot_llmcloud_dot_shimmanager_dot_v1_dot_shim__service__pb2.ShimServiceGetQueryResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'public.llmcloud.shimmanager.v1.ShimService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ShimService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/public.llmcloud.shimmanager.v1.ShimService/GetQuery',
            public_dot_llmcloud_dot_shimmanager_dot_v1_dot_shim__service__pb2.ShimServiceGetQueryRequest.SerializeToString,
            public_dot_llmcloud_dot_shimmanager_dot_v1_dot_shim__service__pb2.ShimServiceGetQueryResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
